version: '3.4'
services:
  app:
    container_name: app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 6069 --reload
    volumes:
      - demo-volume:/app
    ports:
      - 6069:6069
    restart: always
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery --app celery_queue worker --loglevel=info --pool=solo  -E --logfile=logs/celery_main.log
    volumes:
      - demo-volume:/app
    depends_on:
      - app
volumes:
 demo-volume:
   #external: true
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/app