version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 6069 --reload
    volumes:
      - ./myapp:/app
    ports:
      - 6069:6069
    restart: always
    depends_on:
      - redis
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery --app celery_queue worker --loglevel=info --pool=solo -f celery.log
    volumes:
      - ./myapp:/app
    depends_on:
      - redis
      - app
volumes:
  myapp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/myapp